name: My CI Pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.8

      - name: Install dependencies
        run: cd client 
        
      - name: Install w npm
        run: npm install

      - name: Build webapp
        run: npm run build

      - name: Deploy to Skynet
        uses: SkynetLabs/deploy-to-skynet-action@v2.0.2
        with:
          upload-dir: build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.REGISTRY_SEED || '' }}
