name: Skynet Frontend pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.8
        
      - name: Installs npm
        run: npm install -g npm@7.24.2
        
      - name: Installs dependencies
        run: cd client && yarn
        
      - name: Runs npm build task - g build dir
        run: cd client && CI= npm run build
      

      - name: Deploy to Skynet
        uses: SkynetLabs/deploy-to-skynet-action@v2.0.2
        with:
          upload-dir: client/build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.REGISTRY_SEED || '' }}
